name: Build and Upload Artifacts
description: Build and upload artifacts for all the packages

runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: yarn lerna run build --since=origin/master --include-dependencies
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ci-builds-${{ github.run_id }}-${{ github.run_attempt }}
        path: |
          packages/core/dist/
          packages/style/dist/
        if-no-files-found: ignore
