name: Build and Upload Artifacts

on:
  workflow_call:
    secrets:
      npm_token:
        required: true

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Setup
        uses: ./.github/actions/setup
        with:
          npm_token: ${{ secrets.npm_token }}
      - id: determine-since-flag
        uses: ./.github/actions/determine-lerna-since-flag
      - name: Build
        shell: bash
        env:
          SINCE_FLAG: ${{ steps.determine-since-flag.outputs.since_flag }}
        run: yarn lerna run build $SINCE_FLAG --include-dependencies
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ci-builds-${{ github.run_id }}-${{ github.run_attempt }}
          path: |
            packages/core/dist/
            packages/style/dist/
          if-no-files-found: ignore
