name: "Chromatic"

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Setup
        uses: ./.github/actions/setup
        with:
          npm_token: ${{ secrets.npm_token }}
      - id: check-changed-packages
        uses: ./.github/actions/check-changed-packages
        with:
          exit_code_on_no_changes: 0
      - id: determine-since-flag
        uses: ./.github/actions/determine-lerna-since-flag
      - name: Run Build
        shell: bash
        env:
          SINCE_FLAG: ${{ steps.determine-since-flag.outputs.since_flag }}
        run: yarn lerna run build $SINCE_FLAG --include-filtered-dependencies
      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken, if you are project maintainer refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/core
