name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - users: ./github/workflows/setup.yml
        secrets:
          npm_token: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run lint

  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run stylelint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run build

  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run build-storybook
