name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/setup
        with:
          npm_token: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run test --since=master

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run lint --since=master

  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run stylelint --since=master

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run build --since=master

  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run build-storybook --since=master
