name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          npm_token: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          npm_token: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run lint

  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          npm_token: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run stylelint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          npm_token: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run build

  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          npm_token: ${{secrets.npm_token}}
      - name: Test
        run: yarn lerna run build-storybook
