name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ["Test", "Lint", "Stylelint", "Build", "Build Storybook"]
        command: ["test", "lint", "stylelint", "build", "build-storybook"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          npm_token: ${{secrets.npm_token}}
      - name: ${{matrix.step_name}}
        shell: bash
        run: yarn lerna run ${{matrix.step_command}} --since=master
