name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-and-upload.yml
    secrets:
      npm_token: ${{ secrets.npm_token }}
  ci:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Test"
            command: "test"
          - name: "Lint"
            command: "lint"
          - name: "Stylelint"
            command: "stylelint"
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Setup
        uses: ./.github/actions/setup
        with:
          npm_token: ${{secrets.npm_token}}
      - uses: ./.github/actions/download-builds
      - name: Run ${{matrix.name}}
        shell: bash
        run: yarn lerna run ${{matrix.command}} --since=origin/master

  build-storybook:
    needs: [build, ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Setup
        uses: ./.github/actions/setup
        with:
          npm_token: ${{secrets.npm_token}}
      - uses: ./.github/actions/download-builds
      - name: Build Storybook
        run: yarn lerna run build-storybook --since=origin/master
