name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Test"
            command: "test"
          - name: "Lint"
            command: "lint"
          - name: "Stylelint"
            command: "stylelint"
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Setup
        uses: ./.github/actions/setup
        with:
          npm_token: ${{secrets.npm_token}}
      - name: Run ${{matrix.name}}
        shell: bash
        run: yarn lerna run ${{matrix.command}} --since=origin/master

  build-storybook:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Setup
        uses: ./.github/actions/setup
        with:
          npm_token: ${{secrets.npm_token}}
      - name: Run Build
        shell: bash
        run: yarn lerna run build --since=origin/master --include-filtered-dependencies
      - name: Build Storybook
        run: yarn lerna run build-storybook --since=origin/master
