# This workflow will ensure all PRs are labeled so we can later create releases

name: PR labeling for release

on: [pull_request]

jobs:
  ensure-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels action step
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["PR: Bugfix 🐛", "PR: New Feature 🕹", "PR: Dependencies 🛠", "PR: Documentation 📖", "PR: Internal 🏠"]'
      - name: See result
        run: echo "${{ steps.check_pr_labels.outputs.result }}"
