name: PR Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-and-upload.yml
    secrets:
      npm_token: ${{ secrets.npm_token }}

  test:
    name: Test
    needs: build
    if: ${{ needs.build.outputs.has_changes == 'true' }}
    uses: ./.github/workflows/test.yml
    secrets:
      npm_token: ${{ secrets.npm_token }}

  commitlint:
    name: Commit Lint
    needs: build
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
