name: Publish Storybooks

on:
  workflow_run:
    workflows: ["Release new version"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Build & deploy Storybooks to GitHub Pages
        run: |
          yarn
          yarn lerna run build --since --include-dependencies
          yarn lerna run --scope monday-ui-react-core build-storybook
          yarn lerna run --scope monday-ui-style build-storybook
          cd packages/core/static_storybook
          echo "style.monday.com" > ./CNAME
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
      - name: Push style Storybook to Github Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: packages/style/storybook-static
          branch: gh-pages
          target-folder: style
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push core Storybook to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean-exclude: style/*
          folder: packages/core/static_storybook
          branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
