name: Release new version

on: workflow_dispatch

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Set up git credentials
        run: |
          git config --global user.name 'ci'
          git config --global user.email 'deploy@monday.com'
      - name: Prepare changes
        run: npm run release
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push changes
        run: |
          git add .
          echo "package_version=$(node -e "console.log(require('./package.json').version)")" >> "$GITHUB_ENV"
          echo "Release version ${{ env.package_version }}"
